import { appendFileSync, writeFileSync } from 'fs';
import { BPS_DENOMINATOR, computeFeeSplit, computePlayerWinPayout, computeTotalFee, computeTotalWinLiability, formatUnits, SOL_FEE_CONFIG, TOKEN_FEE_CONFIG } from './feeMath';
import { Asset, AssetAccounting, BetChoice, FeeConfig, InvariantViolation, MonteCarloOptions, SimBet, SimulationResult } from './types';

class Rng {
  constructor(private state: bigint) { if (state === 0n) this.state = 1n; }
  next(): bigint { let x = this.state; x ^= x << 13n; x ^= x >> 7n; x ^= x << 17n; this.state = x & ((1n << 64n) - 1n); return this.state; }
  bps(): bigint { return this.next() % BPS_DENOMINATOR; }
  int(maxExclusive: number): number { return Number(this.next() % BigInt(maxExclusive)); }
  range(min: bigint, max: bigint): bigint { if (max <= min) return min; return min + (this.next() % (max - min + 1n)); }
}

const ZERO_SPLIT = { total: 0n, team: 0n, dev: 0n, burn: 0n, holderRewards: 0n };

function acct(asset: Asset, bankroll: bigint): AssetAccounting {
  return { asset, houseVaultBalance: bankroll, initialHouseVaultBalance: bankroll, outstandingLiability: 0n, totalWagered: 0n, totalPlayerPayouts: 0n, totalFees: 0n, teamFees: 0n, devFees: 0n, burnFees: 0n, holderRewardsFees: 0n, totalRefunded: 0n, totalHouseProfit: 0n, maxDrawdown: 0n, minVaultBalance: bankroll, maxOutstandingLiability: 0n, rejectedBets: 0n, acceptedBets: 0n, settledBets: 0n, refundedBets: 0n, openBets: 0n, wins: 0n, losses: 0n };
}

export class MonteCarloSimulator {
  private rng: Rng; private id = 0n; private open = new Map<string, SimBet>();
  readonly sol: AssetAccounting; readonly token: AssetAccounting; readonly violations: InvariantViolation[] = [];
  constructor(readonly options: MonteCarloOptions) { this.rng = new Rng(options.seed); this.sol = acct('SOL', options.solBankroll); this.token = acct('BABY_KENJI', options.tokenBankroll); }
  run(): SimulationResult { for (let step = 0; step < this.options.iterations; step++) { this.processDue(step); let placementAttempts = 0; while (this.open.size < this.options.concurrency && placementAttempts < this.options.concurrency * 4) { this.place(step); placementAttempts++; } this.assertGlobal(step); } this.processDue(this.options.iterations + this.options.settlementDelayMax + 2, true); this.assertGlobal(this.options.iterations); return { scenario: this.options.scenario, seed: this.options.seed.toString(), iterations: this.options.iterations, assetMode: this.options.asset, sol: this.sol, token: this.token, invariantViolations: this.violations, passed: this.violations.length === 0 }; }
  private cfg(asset: Asset): FeeConfig { return asset === 'SOL' ? SOL_FEE_CONFIG : TOKEN_FEE_CONFIG; }
  private a(asset: Asset): AssetAccounting { return asset === 'SOL' ? this.sol : this.token; }
  private chooseAsset(): Asset { return this.options.asset === 'sol' ? 'SOL' : this.options.asset === 'token' ? 'BABY_KENJI' : (this.rng.int(2) === 0 ? 'SOL' : 'BABY_KENJI'); }
  private amount(asset: Asset): bigint { const min = asset === 'SOL' ? this.options.minSolBet : this.options.minTokenBet; const max = asset === 'SOL' ? this.options.maxSolBet : this.options.maxTokenBet; switch (this.options.betSizeMode) { case 'small': return this.rng.range(min, min + (max - min) / 20n); case 'large': return this.rng.range(min + ((max - min) * 80n) / 100n, max); case 'max': case 'whale': return max; case 'mixed': return this.rng.int(3) === 0 ? min : this.rng.int(2) === 0 ? max : this.rng.range(min, max); default: return this.rng.range(min, max); } }
  place(step: number, amountOverride?: bigint, assetOverride?: Asset): SimBet { const asset = assetOverride ?? this.chooseAsset(); const a = this.a(asset); const cfg = this.cfg(asset); const amount = amountOverride ?? this.amount(asset); const id = ++this.id; const rejected = (why: string): SimBet => { a.rejectedBets++; return { id, asset, amount, choice: 0, status: 'rejected', placedAtStep: step, settlementStep: step, refundDeadlineStep: step, feeBreakdown: ZERO_SPLIT, playerWinPayout: 0n, totalWinLiability: 0n, feeRecipientsSnapshot: { team: 'team', dev: 'dev', holderRewards: 'holders', burn: 'burn' } }; };
    const min = asset === 'SOL' ? this.options.minSolBet : this.options.minTokenBet, max = asset === 'SOL' ? this.options.maxSolBet : this.options.maxTokenBet;
    if (amount < min || amount > max || computeTotalFee(amount, cfg.totalFeeBps) === 0n) return rejected('bounds-or-zero-fee');
    const feeBreakdown = computeFeeSplit(amount, cfg), playerWinPayout = computePlayerWinPayout(amount, cfg.totalFeeBps), totalWinLiability = computeTotalWinLiability(amount, cfg);
    const rent = asset === 'SOL' ? this.options.solRentReserve : 0n;
    if (a.houseVaultBalance + amount < a.outstandingLiability + totalWinLiability + rent) return rejected('insufficient-bankroll');
    const delay = this.options.settlementDelayMin + this.rng.int(Math.max(1, this.options.settlementDelayMax - this.options.settlementDelayMin + 1));
    const bet: SimBet = { id, asset, amount, choice: this.rng.int(2) as BetChoice, status: 'open', placedAtStep: step, settlementStep: step + delay, refundDeadlineStep: step + delay + 1, feeBreakdown, playerWinPayout, totalWinLiability, feeRecipientsSnapshot: { team: 'team', dev: 'dev', holderRewards: 'holders', burn: 'burn' } };
    a.houseVaultBalance += amount; a.outstandingLiability += totalWinLiability; a.totalWagered += amount; a.acceptedBets++; a.openBets++; a.maxOutstandingLiability = a.outstandingLiability > a.maxOutstandingLiability ? a.outstandingLiability : a.maxOutstandingLiability; this.open.set(id.toString(), bet); this.track(a); return bet; }
  settle(bet: SimBet, step: number): void { const a = this.a(bet.asset); if (bet.status !== 'open') throw new Error(`duplicate settlement/refund for bet ${bet.id}`); bet.status = 'settled'; a.outstandingLiability -= bet.totalWinLiability; const won = this.didWin(step); bet.won = won; bet.resultBit = won ? bet.choice : ((1 - bet.choice) as BetChoice); if (won) { a.houseVaultBalance -= bet.playerWinPayout; a.totalPlayerPayouts += bet.playerWinPayout; a.wins++; } else a.losses++; a.houseVaultBalance -= bet.feeBreakdown.team + bet.feeBreakdown.dev + bet.feeBreakdown.burn + bet.feeBreakdown.holderRewards; a.totalFees += bet.feeBreakdown.total; a.teamFees += bet.feeBreakdown.team; a.devFees += bet.feeBreakdown.dev; a.burnFees += bet.feeBreakdown.burn; a.holderRewardsFees += bet.feeBreakdown.holderRewards; a.settledBets++; a.openBets--; this.open.delete(bet.id.toString()); this.track(a); }
  refund(bet: SimBet): void { const a = this.a(bet.asset); if (bet.status !== 'open') throw new Error(`duplicate settlement/refund for bet ${bet.id}`); bet.status = 'refunded'; a.outstandingLiability -= bet.totalWinLiability; a.houseVaultBalance -= bet.amount; a.totalRefunded += bet.amount; a.refundedBets++; a.openBets--; this.open.delete(bet.id.toString()); this.track(a); }
  withdrawable(asset: Asset): bigint { const a = this.a(asset); const rent = asset === 'SOL' ? this.options.solRentReserve : 0n; const w = a.houseVaultBalance - a.outstandingLiability - rent; return w > 0n ? w : 0n; }
  private processDue(step: number, drain = false): void { for (const bet of [...this.open.values()]) { if (drain || step >= bet.settlementStep) { if (this.rng.bps() < this.options.unresolvedRate || this.rng.bps() < this.options.refundRate) this.refund(bet); else this.settle(bet, step); } } }
  private didWin(step: number): boolean { const s = this.options.forcedStreak; const n = this.options.forcedStreakLength; if (s !== 'none' && step < n) return s === 'wins' ? true : s === 'losses' ? false : step % 2 === 0; return this.rng.bps() < this.options.winRate; }
  private track(a: AssetAccounting): void { if (a.houseVaultBalance < a.minVaultBalance) a.minVaultBalance = a.houseVaultBalance; const dd = a.initialHouseVaultBalance > a.houseVaultBalance ? a.initialHouseVaultBalance - a.houseVaultBalance : 0n; if (dd > a.maxDrawdown) a.maxDrawdown = dd; a.totalHouseProfit = a.houseVaultBalance - a.initialHouseVaultBalance; }
  private assertGlobal(step: number): void { for (const a of [this.sol, this.token]) { const rent = a.asset === 'SOL' ? this.options.solRentReserve : 0n; const bad = (inv: string, msg: string) => this.violations.push({ step, asset: a.asset, invariant: inv, message: msg, state: { vault: a.houseVaultBalance.toString(), liability: a.outstandingLiability.toString() } }); if (a.outstandingLiability < 0n) bad('nonnegative-liability', 'outstanding liability went negative'); if (a.houseVaultBalance < 0n) bad('nonnegative-vault', 'vault went negative'); if (a.houseVaultBalance < rent) bad('rent-reserve', 'SOL vault below rent reserve'); if (this.withdrawable(a.asset) > a.houseVaultBalance - a.outstandingLiability) bad('withdrawable-safety', 'withdrawable includes liability'); if (a.asset === 'SOL' && a.burnFees !== 0n) bad('sol-no-burn', 'SOL burn was recorded'); } }
}

export function defaultOptions(overrides: Partial<MonteCarloOptions> = {}): MonteCarloOptions { return { scenario: 'baseline', seed: 42n, iterations: 10_000, asset: 'mixed', solBankroll: 1_000_000_000_000n, tokenBankroll: 1_000_000_000_000_000n, minSolBet: 10_000n, maxSolBet: 1_000_000_000n, minTokenBet: 10_000n, maxTokenBet: 1_000_000_000_000n, concurrency: 20, settlementDelayMin: 1, settlementDelayMax: 5, refundRate: 50n, unresolvedRate: 0n, winRate: 5000n, betSizeMode: 'uniform', forcedStreak: 'none', forcedStreakLength: 0, runs: 1, json: false, solRentReserve: 0n, ...overrides }; }

function scenarioOptions(name: string): Partial<MonteCarloOptions> { const m: Record<string, Partial<MonteCarloOptions>> = { baseline: {}, 'max-win-streak': { forcedStreak: 'wins', forcedStreakLength: 1_000, betSizeMode: 'max' }, 'max-loss-streak': { forcedStreak: 'losses', forcedStreakLength: 1_000, betSizeMode: 'max' }, 'high-concurrency': { concurrency: 500, settlementDelayMin: 20, settlementDelayMax: 100 }, 'refund-storm': { refundRate: 8000n, unresolvedRate: 5000n }, 'dust-attack': { minSolBet: 1n, maxSolBet: 20_000n, minTokenBet: 1n, maxTokenBet: 20_000n, betSizeMode: 'small' }, 'whale-pressure': { betSizeMode: 'whale', concurrency: 100 }, 'mixed-asset-chaos': { asset: 'mixed', betSizeMode: 'mixed', refundRate: 1000n, settlementDelayMax: 50, concurrency: 200 }, 'admin-withdrawal-pressure': { concurrency: 500, settlementDelayMax: 100 }, 'rounding-fuzz': { minSolBet: 1n, maxSolBet: 10_000_000_000_000n, minTokenBet: 1n, maxTokenBet: 10_000_000_000_000n, betSizeMode: 'mixed' } }; return { scenario: name, ...(m[name] ?? {}) }; }

function parseArgs(argv: string[]): MonteCarloOptions { const o: any = {}; for (let i = 0; i < argv.length; i++) { const k = argv[i]; if (!k.startsWith('--')) continue; const key = k.slice(2).replace(/-([a-z])/g, (_, c) => c.toUpperCase()); const val = argv[i + 1]?.startsWith('--') || argv[i + 1] == null ? 'true' : argv[++i]; o[key] = val; } const scen = o.scenario ?? 'baseline'; const opts: any = { ...scenarioOptions(scen) }; for (const [k, v] of Object.entries(o)) opts[k] = v; for (const k of ['seed','solBankroll','tokenBankroll','minSolBet','maxSolBet','minTokenBet','maxTokenBet','refundRate','unresolvedRate','winRate','solRentReserve']) if (opts[k] != null) opts[k] = BigInt(opts[k]); for (const k of ['iterations','concurrency','settlementDelayMin','settlementDelayMax','forcedStreakLength','runs']) if (opts[k] != null) opts[k] = Number(opts[k]); opts.json = opts.json === true || opts.json === 'true'; return defaultOptions(opts); }
function replacer(_: string, v: unknown) { return typeof v === 'bigint' ? v.toString() : v; }
function printResult(r: SimulationResult): void { const line = (a: AssetAccounting, decimals: number) => `  Accepted bets: ${a.acceptedBets}\n  Rejected bets: ${a.rejectedBets}\n  Wins: ${a.wins}\n  Losses: ${a.losses}\n  Refunds: ${a.refundedBets}\n  Total wagered: ${formatUnits(a.totalWagered, decimals)}\n  Player payouts: ${formatUnits(a.totalPlayerPayouts, decimals)}\n  Team fees: ${formatUnits(a.teamFees, decimals)}\n  Dev fees: ${formatUnits(a.devFees, decimals)}\n  Burned: ${formatUnits(a.burnFees, decimals)}\n  Holder rewards: ${formatUnits(a.holderRewardsFees, decimals)}\n  Ending vault: ${formatUnits(a.houseVaultBalance, decimals)}\n  Outstanding liability: ${formatUnits(a.outstandingLiability, decimals)}\n  Max liability: ${formatUnits(a.maxOutstandingLiability, decimals)}\n  Min vault: ${formatUnits(a.minVaultBalance, decimals)}\n  Max drawdown: ${formatUnits(a.maxDrawdown, decimals)}\n  Realized house edge: ${a.totalWagered === 0n ? 'n/a' : `${(Number((a.totalHouseProfit * 1_000_000n) / a.totalWagered) / 10_000).toFixed(4)}%`}`;
  console.log(`Monte Carlo Coin Flip Economic Simulation\n\nScenario: ${r.scenario}\nSeed: ${r.seed}\nIterations: ${r.iterations.toLocaleString()}\nAsset mode: ${r.assetMode}\n\nSOL:\n${line(r.sol, 9)}\n\nBABY_KENJI:\n${line(r.token, 6)}\n\nInvariant checks:\n  ${r.passed ? '✅' : '❌'} fee splits sum exactly\n  ${r.passed ? '✅' : '❌'} no negative vaults\n  ${r.passed ? '✅' : '❌'} no unresolved liability leak\n  ${r.passed ? '✅' : '❌'} refunds charged no fees\n  ${r.passed ? '✅' : '❌'} burn only happened for token flips\n  ${r.passed ? '✅' : '❌'} withdrawable never included liability`); if (!r.passed) console.error(JSON.stringify(r.invariantViolations, replacer, 2)); }
export function runCli(argv = process.argv.slice(2)): SimulationResult { const opts = parseArgs(argv); const sim = new MonteCarloSimulator(opts); const res = sim.run(); if (opts.csvOut) { const header = 'scenario,seed,iterations,asset,accepted,rejected,wins,losses,refunds,totalWagered,endingVault,outstandingLiability,passed\n'; try { writeFileSync(opts.csvOut, header); } catch {} for (const a of [res.sol, res.token]) appendFileSync(opts.csvOut, `${res.scenario},${res.seed},${res.iterations},${a.asset},${a.acceptedBets},${a.rejectedBets},${a.wins},${a.losses},${a.refundedBets},${a.totalWagered},${a.houseVaultBalance},${a.outstandingLiability},${res.passed}\n`); } if (opts.json) console.log(JSON.stringify(res, replacer, 2)); else printResult(res); if (!res.passed) process.exitCode = 1; return res; }
if (require.main === module) runCli();
